---

TYPO3:
  Flow:
    http:
      chain:
        'process':
          chain:
            'redirects':
              position: 'start'
              component: 'SimplyAdmire\Redirects\Mvc\Routing\RedirectComponent'
              componentOptions: []
